### ISSUE TITLE
[ical-json] first week's "days" are an object, while other weeks are an array

### ISSUE THREAD

**Issue by oxypomme** [WildGoat07/Wildgoat-API#2]
+ first week's "days" have 11 days.

Example : ![ex](https://i.imgur.com/14qx3yw.png)

**Comment by oxypomme** [comment]
When running in localhost
![](https://i.imgur.com/yUZylA7.png)

**Comment by Wiltoga** [comment]
ok for some reason [this pull request](https://github.com/WildGoat07/Wildgoat-API/pull/4) fixed the problem
